sudo: required
dist: bionic # (18.04)

language: cpp

cache: ccache

addons:
  apt:
    update: true

services:
  - mysql
  - docker

git:
  depth: 10

stages:
  - prepare_cache
  - run

jobs:
  include:
    - stage: prepare_cache
      env: TRAVIS_BUILD_ID="1"
      before_install:
        - git clone --depth 100 https://github.com/azerothcore/azerothcore-wotlk.git AC && cd AC
        - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh OFF
        - source ./apps/ci/ci-install-modules.sh
      script:
        - source ./apps/ci/ci-compile.sh

    - stage: run
      env: TRAVIS_BUILD_ID="1"
      before_install:
        - git clone --depth 100 https://github.com/azerothcore/azerothcore-wotlk.git AC && cd AC
        - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh ON
        - source ./apps/ci/ci-install-modules.sh
        - source ./apps/ci/ci-import-db.sh
      script:
        - source ./apps/ci/ci-compile.sh
        - source ./apps/ci/ci-worldserver-dry-run.sh

    - stage: prepare_cache
      env: TRAVIS_BUILD_ID="2"
      before_install:
        - git clone --depth 100 https://github.com/azerothcore/azerothcore-wotlk.git AC && cd AC
        - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh OFF
        - source ./apps/ci/ci-install-modules.sh
      script:
        - source ./apps/ci/ci-compile.sh

    - stage: run
      env: TRAVIS_BUILD_ID="2"
      before_install:
        - git clone --depth 100 https://github.com/azerothcore/azerothcore-wotlk.git AC && cd AC
        - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh ON
        - source ./apps/ci/ci-install-modules.sh
      script:
        - source ./apps/ci/ci-compile.sh

    - stage: run
      env: TRAVIS_BUILD_ID="3"
      before_install:
        - git clone --depth 100 https://github.com/azerothcore/azerothcore-wotlk.git AC && cd AC
      script:
        - ./apps/ci/docker/ci-docker-config.sh
        - ./bin/acore-docker-generate-etc
        - ./bin/acore-docker-build-no-scripts
        - docker-compose up -d ac-database